language: rust
sudo: 9000
dist: trusty
rust:
  - nightly

env:
  - FEATURES=""
  - FEATURES="debugmozjs"

script:
  - cargo build --verbose --features "$FEATURES"
  - cargo test --verbose --features "$FEATURES"

branches:
  except:
    - master
notifications:
  webhooks: http://build.servo.org:54856/travis
